/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Stanica;
import domen.StavkaProgramskogVodica;
import domen.TipEmisije;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import transfer.Komunikacija;
import transfer.Odgovor;
import transfer.Operacija;
import transfer.Zahtev;

/**
 *
 * @author Danilo
 */
public class DodajStavkuProgramskogVodica extends javax.swing.JDialog {

    /**
     * Creates new form DodajStavkuProgramskogVodica
     */
    public DodajStavkuProgramskogVodica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniStanice();
        popuniTipove();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbStanica = new javax.swing.JComboBox();
        cmbPodtip = new javax.swing.JComboBox();
        cmbTip = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRedniBroj = new javax.swing.JTextField();
        txtNazivEmisije = new javax.swing.JTextField();
        txtDatumVremeOd = new javax.swing.JTextField();
        txtDatumVremeDo = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Stanica");

        jLabel2.setText("Tip emisije");

        jLabel3.setText("Podtip emisije");

        cmbStanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPodtip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPodtip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPodtipActionPerformed(evt);
            }
        });

        cmbTip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipItemStateChanged(evt);
            }
        });
        cmbTip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTipMouseClicked(evt);
            }
        });
        cmbTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipActionPerformed(evt);
            }
        });

        jLabel4.setText("Redni broj");

        jLabel5.setText("Datum i vreme od");

        jLabel6.setText("Datum i vreme do");

        jLabel7.setText("Naziv emisije");

        btnDodajStavku.setText("Dodaj stavku programskog vodica");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDodajStavku)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtRedniBroj))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbStanica, 0, 205, Short.MAX_VALUE)
                                .addComponent(cmbTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbPodtip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatumVremeOd, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtDatumVremeDo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNazivEmisije))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbStanica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPodtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRedniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNazivEmisije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatumVremeOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDatumVremeDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodajStavku)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPodtipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPodtipActionPerformed

    }//GEN-LAST:event_cmbPodtipActionPerformed

    private void cmbTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipActionPerformed

    }//GEN-LAST:event_cmbTipActionPerformed

    private void cmbTipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipMouseClicked

    }//GEN-LAST:event_cmbTipMouseClicked

    private void cmbTipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipItemStateChanged
        TipEmisije izabraniNadtip = (TipEmisije) cmbTip.getSelectedItem();

        if (izabraniNadtip!=null)
            popuniPodtipove(izabraniNadtip);
    }//GEN-LAST:event_cmbTipItemStateChanged

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        int rb = Integer.parseInt(txtRedniBroj.getText());
        String nazivEmisije = txtNazivEmisije.getText();
        Date datumVremeOd;
        Date datumVremeDo;
        Stanica stanica =(Stanica) cmbStanica.getSelectedItem();
        TipEmisije tipEmisije = (TipEmisije) cmbPodtip.getSelectedItem();
        try {
            datumVremeOd = sdf.parse(txtDatumVremeOd.getText());
            datumVremeDo = sdf.parse(txtDatumVremeDo.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "DAtum i vremem mora biti u formatu dd.MM.yyyy HH:mm");
            return;
        }
        StavkaProgramskogVodica spv = new StavkaProgramskogVodica(rb, nazivEmisije, datumVremeOd, datumVremeDo, stanica, tipEmisije);
        GlavnaForma gf = (GlavnaForma) getParent();
        gf.dodajStavku(spv);
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public void popuniPodtipove(TipEmisije izabraniNadtip) throws HeadlessException {
        TipEmisije nadtip = izabraniNadtip;
        cmbPodtip.removeAllItems();
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_PODTIPOVE, nadtip));
        Odgovor odg = Komunikacija.getInstance().primiOdgovor();
        if (odg.getParamtera() == null) {
            JOptionPane.showMessageDialog(this, odg.getPoruka());
        } else {
            ArrayList<TipEmisije> listaTipova = (ArrayList<TipEmisije>) odg.getParamtera();
            for (TipEmisije tip : listaTipova) {
                cmbPodtip.addItem(tip);
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JComboBox cmbPodtip;
    private javax.swing.JComboBox cmbStanica;
    private javax.swing.JComboBox cmbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDatumVremeDo;
    private javax.swing.JTextField txtDatumVremeOd;
    private javax.swing.JTextField txtNazivEmisije;
    private javax.swing.JTextField txtRedniBroj;
    // End of variables declaration//GEN-END:variables

    private void popuniStanice() {
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_STANICE, null));
        cmbStanica.removeAllItems();
        Odgovor odg = Komunikacija.getInstance().primiOdgovor();
        if (odg.getParamtera() == null) {
            JOptionPane.showMessageDialog(this, odg.getPoruka());
        } else {
            ArrayList<Stanica> listaStan = (ArrayList<Stanica>) odg.getParamtera();
            for (Stanica stanica : listaStan) {
                cmbStanica.addItem(stanica);
            }

        }
    }

    private void popuniTipove() {
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_TIPOVE, null));
        cmbTip.removeAllItems();
        Odgovor odg = Komunikacija.getInstance().primiOdgovor();
        if (odg.getParamtera() == null) {
            JOptionPane.showMessageDialog(this, odg.getPoruka());
        } else {
            ArrayList<TipEmisije> listaTipova = (ArrayList<TipEmisije>) odg.getParamtera();
            for (TipEmisije tip : listaTipova) {
                cmbTip.addItem(tip);
            }

        }
    }
}
