/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Komponenta;
import domen.Pogon;
import domen.PrevoznoSredstvo;
import domen.Rukovodilac;
import java.security.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.KlijentskiZahtev;
import komunikacija.Operacija;
import komunikacija.ServerskiOdgovor;

/**
 *
 * @author Danilo
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        popuniRukovodioca();
        popuniTipove();
        popuniDatum();
        popuniPogone();
        tblKomponente.setModel(new ModelTabeleKomponenti());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRukovodilac = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtPocetak = new javax.swing.JTextField();
        txtZavrsetak = new javax.swing.JTextField();
        txtOcekivaniVek = new javax.swing.JTextField();
        cmbTip = new javax.swing.JComboBox<>();
        cmbPogon = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKomponente = new javax.swing.JTable();
        btmDodajKomponentu = new javax.swing.JButton();
        btnObrisiKomponentu = new javax.swing.JButton();
        btnSacuvajPrevoznoSredstvo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fon auto - Klijentski program");

        jLabel1.setText("Model");

        jLabel2.setText("Datum i vreme pocetka proizvodnje");

        jLabel3.setText("Datum i vreme zavrsetka proizvodnje");

        jLabel4.setText("Ocekivani radni vek (Godina)");

        jLabel5.setText("Tip prevoznog sredstva");

        jLabel6.setText("Proizvodni pogon");

        jLabel7.setText("Rukovodilac");

        txtRukovodilac.setEditable(false);

        txtPocetak.setText("TREBA DA STOJI SADASNJE VREME");

        cmbTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPogon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblKomponente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKomponente);

        btmDodajKomponentu.setText("Dodaj komponentu");
        btmDodajKomponentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDodajKomponentuActionPerformed(evt);
            }
        });

        btnObrisiKomponentu.setText("Obrisi komponentu");
        btnObrisiKomponentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiKomponentuActionPerformed(evt);
            }
        });

        btnSacuvajPrevoznoSredstvo.setText("Sacuvaj prevozno sredstvo");
        btnSacuvajPrevoznoSredstvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPrevoznoSredstvoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btmDodajKomponentu)
                                .addGap(18, 18, 18)
                                .addComponent(btnObrisiKomponentu))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbTip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(160, 160, 160)
                                    .addComponent(txtModel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPocetak, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                        .addComponent(txtZavrsetak)
                                        .addComponent(txtOcekivaniVek)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbPogon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRukovodilac)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacuvajPrevoznoSredstvo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPocetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtZavrsetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOcekivaniVek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPogon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRukovodilac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmDodajKomponentu)
                    .addComponent(btnObrisiKomponentu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajPrevoznoSredstvo)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmDodajKomponentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDodajKomponentuActionPerformed
        DodajKomponentuForma dkf = new DodajKomponentuForma(this, true);
        dkf.setVisible(true);
    }//GEN-LAST:event_btmDodajKomponentuActionPerformed

    private void btnObrisiKomponentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiKomponentuActionPerformed
        ModelTabeleKomponenti mtk =  (ModelTabeleKomponenti) tblKomponente.getModel();
        int row =  tblKomponente.getSelectedRow();
        mtk.obrisi(row);
    }//GEN-LAST:event_btnObrisiKomponentuActionPerformed

    private void btnSacuvajPrevoznoSredstvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPrevoznoSredstvoActionPerformed
        ModelTabeleKomponenti mtk =  (ModelTabeleKomponenti) tblKomponente.getModel();
        String model = txtModel.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy hh:mm");
        Date pocetakProizvodnje = new Date();
        Date zavretakProizvodnje= new Date();
        try {
            pocetakProizvodnje = sdf.parse(txtPocetak.getText());
            zavretakProizvodnje = sdf.parse(txtZavrsetak.getText());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum!");
        }
        int ocekivaniRadniVek = Integer.parseInt(txtOcekivaniVek.getText());
        String tip = (String) cmbTip.getSelectedItem();
        Pogon pogon = (Pogon) cmbPogon.getSelectedItem();
        Rukovodilac rukovodilac = session.Session.getInstance().getUlogovani();
        ArrayList<Komponenta> komponente = mtk.getLista();
        PrevoznoSredstvo ps =new PrevoznoSredstvo(-1, model, pocetakProizvodnje, zavretakProizvodnje, ocekivaniRadniVek, tip, pogon, rukovodilac, komponente);
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacija.SACUVAJ_PREVOZNO_SREDSTVO, ps);
        komunikacija.Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        if((boolean)so.getParametar()==false){
        JOptionPane.showMessageDialog(this, "Doslo je do greske");
        }else{
        JOptionPane.showMessageDialog(this, "Uspesno");
        }
        mtk.setLista(new ArrayList<>());
    }//GEN-LAST:event_btnSacuvajPrevoznoSredstvoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmDodajKomponentu;
    private javax.swing.JButton btnObrisiKomponentu;
    private javax.swing.JButton btnSacuvajPrevoznoSredstvo;
    private javax.swing.JComboBox cmbPogon;
    private javax.swing.JComboBox<String> cmbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKomponente;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOcekivaniVek;
    private javax.swing.JTextField txtPocetak;
    private javax.swing.JTextField txtRukovodilac;
    private javax.swing.JTextField txtZavrsetak;
    // End of variables declaration//GEN-END:variables

    private void popuniRukovodioca() {
        txtRukovodilac.setText(session.Session.getInstance().getUlogovani().getKorisnickoIme());
    }

    private void popuniTipove() {
        cmbTip.removeAllItems();
        cmbTip.addItem("Autmobil");
        cmbTip.addItem("Kombi");
        cmbTip.addItem("Kamion");
        cmbTip.addItem("Autobus");
    }

    private void popuniDatum() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy hh:mm");
        Date now = new Date();

        txtPocetak.setText(String.valueOf(sdf.format(now)));
    }

    private void popuniPogone() {
        cmbPogon.removeAllItems();
        ArrayList<Pogon> lista;
        komunikacija.Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacija.VRATI_POGONE, null));
        ServerskiOdgovor so = komunikacija.Komunikacija.getInstance().primiOdgovor();
        lista = (ArrayList<Pogon>) so.getParametar();
        if (so == null) {
            JOptionPane.showMessageDialog(this, "Greska prilikom ucitavanja pogona");
        } else {

            for (Pogon pogon : lista) {
                cmbPogon.addItem(pogon);
            }
        }
    }

    void dodajKomponentu(Komponenta komponenta) {
        ModelTabeleKomponenti mtk = (ModelTabeleKomponenti) tblKomponente.getModel();
        mtk.add(komponenta);
    }
}
