/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domen.Poruka;
import domen.User;
import form.modeli.ModeltabelePoruka;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import logika.Kontroler;
import transfer.Komunikacija;
import transfer.Operacija;
import transfer.Zahtev;

/**
 *
 * @author Danilo
 */
public class GlavnaForma extends javax.swing.JFrame {

    User user;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();

    }

    public GlavnaForma(User user) throws HeadlessException {
        initComponents();
        this.user = user;
        Kontroler.getInstance().setGf(this);
        txtKorisnik.setText("Korisnik: " + user.getIme() + " " + user.getPrezime());
        popnuiKorisnike();
        srediForme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKorisnik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbZaKoga = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPoruke = new javax.swing.JTextArea();
        btnPosalji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrimeljene = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPoslate = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klijentska fomra");

        txtKorisnik.setText("Korisnik");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova poruka"));

        cmbZaKoga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Primalac");

        txtPoruke.setColumns(20);
        txtPoruke.setRows(5);
        jScrollPane1.setViewportView(txtPoruke);

        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPosalji)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbZaKoga, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbZaKoga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPosalji)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblPrimeljene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPrimeljene);

        tblPoslate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPoslate);

        jLabel2.setText("Primljene poruke");

        jLabel3.setText("Poslate poruke");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtKorisnik)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        if (txtPoruke.getText().length() > 200) {
            JOptionPane.showMessageDialog(this, "Poruka ne sme imati vise od 200 karaktera");
        } else {
            String odKoga = user.getUsername();
            String zaKoga = (String) cmbZaKoga.getSelectedItem();
            String textPoruke = txtPoruke.getText();
            Date vremeSlanja = new Date();
            Poruka poruka = new Poruka(odKoga, zaKoga, textPoruke, vremeSlanja);
            Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.POSALJI_PORUKU, poruka));
        }

    }//GEN-LAST:event_btnPosaljiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosalji;
    private javax.swing.JComboBox<String> cmbZaKoga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPoslate;
    private javax.swing.JTable tblPrimeljene;
    private javax.swing.JLabel txtKorisnik;
    private javax.swing.JTextArea txtPoruke;
    // End of variables declaration//GEN-END:variables

    private void popnuiKorisnike() {
        cmbZaKoga.removeAllItems();
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_ULOGOVANE, null));
    }

    public void obradiUlogovane(ArrayList<String> listaUlogovanih) {
        System.out.println("popunjavam ulogovane");
        cmbZaKoga.removeAllItems();
        cmbZaKoga.addItem("svi");
        for (String string : listaUlogovanih) {
            cmbZaKoga.addItem(string);
        }
    }

    public void obradiPorukaPoslata(boolean uspesno) {
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno poslato");
        } else {
            JOptionPane.showMessageDialog(this, "Doslo je do greske");
        }
    }

    private void srediForme() {
        tblPoslate.setModel(new ModeltabelePoruka());
        tblPrimeljene.setModel(new ModeltabelePoruka());
        popuniPrimljenePorukeZaKorisnika();
        popuniPoslatePorukeZaKorisnika();

    }

    private void popuniPrimljenePorukeZaKorisnika() {
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_PRIMLJENE_PORUKE_ZA_KORISNIKA, user));
    }

    public void obradiPrimljene(ArrayList<Poruka> listaPrimljenih) {
        ModeltabelePoruka mta = (ModeltabelePoruka) tblPrimeljene.getModel();
        mta.setListaPoruka(listaPrimljenih);
    }

    private void popuniPoslatePorukeZaKorisnika() {
        Komunikacija.getInstance().posaljiZahtev(new Zahtev(Operacija.VRATI_POSLATE_PORUKE_ZA_KORISNIKA, user));
    }

    public void obradiPoslate(ArrayList<Poruka> listaPoslatih) {
        ModeltabelePoruka mta = (ModeltabelePoruka) tblPoslate.getModel();
        mta.setListaPoruka(listaPoslatih);
    }

}
